-- V1.1.3__dml_changes.sql

-- Example 1: Add a new column safely
ALTER TABLE EMPLOYEE ADD COLUMN IF NOT EXISTS EMP_STATUS STRING;

-- Example 2: Create a new table safely
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    DEPT_ID INT,
    DEPT_NAME STRING,
    CREATED_AT TIMESTAMP
);

-- Example 3: Create or replace a view safely
CREATE OR REPLACE VIEW ACTIVE_EMPLOYEES AS
SELECT EMP_ID, FULL_NAME, EMP_STATUS
FROM EMPLOYEE
WHERE EMP_STATUS = 'ACTIVE';

-- Example 4: Add multiple columns (safe)
ALTER TABLE EMPLOYEE 
    ADD COLUMN IF NOT EXISTS JOIN_DATE DATE,
    ADD COLUMN IF NOT EXISTS SALARY NUMBER(10,2);
